language: php

php:
- 7.1
- 7.2
- nightly

install: composer install

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- ./vendor/phpunit/phpunit/phpunit --coverage-clover clover.xml

after_script:
- ./cc-test-reporter after-build --coverage-input-type clover --id 255a169209bc406bd830e5bacbab0db1e5292bd2feeed0d40e35f36328cbfa2a --exit-code $TRAVIS_TEST_RESULT
